# Generated by Django 4.1.4 on 2023-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.CharField(max_length=100),
        ),
    ]
