# Generated by Django 4.1.4 on 2023-01-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0005_alter_order_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
