# Generated by Django 4.1.4 on 2023-01-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0007_foodorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='total_order_price',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='cart_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartdetails', to='food_order.cart'),
            preserve_default=False,
        ),
    ]
