# Generated by Django 4.1.4 on 2023-01-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0008_remove_foodorder_email_remove_foodorder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='food_order.cart'),
        ),
    ]
