# Generated by Django 4.1.4 on 2023-01-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0009_alter_foodorder_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_details', to='food_order.cart'),
        ),
    ]
