# Generated by Django 4.1.4 on 2023-01-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0011_alter_foodorder_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='food_order.cart'),
        ),
    ]
