# Generated by Django 4.1.4 on 2023-01-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_display', '0002_rename_name_food_name_rename_price_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('1', 'veg'), ('2', 'Non-veg'), ('3', 'Vegan')], default='1', max_length=20),
        ),
    ]
