# Generated by Django 4.1.4 on 2023-01-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_display', '0003_food_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('1', 'veg'), ('2', 'Non-veg'), ('3', 'Vegan')], max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='food_display.food_category'),
            preserve_default=False,
        ),
    ]
