# Generated by Django 4.1.4 on 2023-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_display', '0009_alter_food_description_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-veg'), ('Vegan', 'Vegan')], max_length=20),
        ),
    ]
